// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzvtienphhnldwnvudon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6dnRpZW5waGhubGR3bnZ1ZG9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3OTU5NjksImV4cCI6MjA4NTM3MTk2OX0.xRUMtHxK-mhw2v90WNUrayWs62nmqAMoBMI9f6dkJdA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});